Repository Toloka/dbt-af, pull requests merged in 2025-05, with the labels that each got.

#62 feat: add iceberg compatibility
  dbt_af/parser/dbt_node_model.py
  dbt_af/parser/dbt_source_model.py
Labels: enhancement, question

#64 feat: enhance dbt_run_model with additional CLI options and parameters
  dbt_af/common/constants.py
  dbt_af/common/utils.py
  dbt_af/dags.py
  dbt_af/operators/base.py
  dbt_af/operators/macros.py
  dbt_af/operators/run.py
  docs/docs.md
  docs/static/dbt_run_model.png
Labels: enhancement

#65 feat: enhance venv operator
  dbt_af/operators/venv.py
  dbt_af_functional_tests/conftest.py
  dbt_af_functional_tests/main.py
  dbt_af_functional_tests/test_all_dbt_models_exist.py
Labels: enhancement

#67 fix: isolate `dbt source freshness` run
  README.md
  dbt_af/conf/config.py
  dbt_af/dags.py
  dbt_af/integrations/mcd/callbacks.py
  dbt_af/operators/base.py
  dbt_af/operators/sensors.py
  dbt_af/operators/supplemental.py
  examples/advanced_project.md
  examples/dags/example_advanced_dbt_af_dag.py
  examples/dags/example_dbt_af_dag.py
  tests/airflow_dags/conftest.py
Labels: bug, enhancement
